"""rules: severity level + applies_to

Revision ID: 5412e3af0c9d
Revises: 7fd6e3f7c889
Create Date: 2026-06-27 09:56:57.987171
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5412e3af0c9d'
down_revision: Union[str, None] = '7fd6e3f7c889'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('applies_to', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.drop_column('applies_to')
        batch_op.drop_column('level')

    # ### end Alembic commands ###
