"""rule proposals + rule versions

Revision ID: 5b9e97c3965a
Revises: 9a327c01c739
Create Date: 2026-06-26 22:11:38.784538
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5b9e97c3965a'
down_revision: Union[str, None] = '9a327c01c739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposer_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('target_rule_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('proposed_category', sa.String(), nullable=True),
    sa.Column('proposed_text', sa.String(), nullable=True),
    sa.Column('proposed_amount', sa.Integer(), nullable=True),
    sa.Column('voting_opens_at', sa.String(), nullable=True),
    sa.Column('voting_closes_at', sa.String(), nullable=True),
    sa.Column('frozen', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.String(), nullable=True),
    sa.Column('resolution_detail', sa.String(), nullable=True),
    sa.Column('merged_rule_id', sa.Integer(), nullable=True),
    sa.Column('merged_rule_version_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('draft','pending_review','voting','passed','rejected','expired','cancelled')", name=op.f('ck_rule_proposals_status_valid')),
    sa.CheckConstraint("type IN ('new_rule', 'modify_rule', 'delete_rule')", name=op.f('ck_rule_proposals_type_valid')),
    sa.ForeignKeyConstraint(['merged_rule_id'], ['rules.id'], name=op.f('fk_rule_proposals_merged_rule_id_rules')),
    sa.ForeignKeyConstraint(['proposer_id'], ['members.id'], name=op.f('fk_rule_proposals_proposer_id_members')),
    sa.ForeignKeyConstraint(['target_rule_id'], ['rules.id'], name=op.f('fk_rule_proposals_target_rule_id_rules')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_proposals'))
    )
    with op.batch_alter_table('rule_proposals', schema=None) as batch_op:
        batch_op.create_index('idx_proposals_closes', ['voting_closes_at'], unique=False)
        batch_op.create_index('idx_proposals_proposer', ['proposer_id'], unique=False)
        batch_op.create_index('idx_proposals_status', ['status'], unique=False)

    op.create_table('proposal_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('edited_at', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['members.id'], name=op.f('fk_proposal_comments_author_id_members')),
    sa.ForeignKeyConstraint(['parent_id'], ['proposal_comments.id'], name=op.f('fk_proposal_comments_parent_id_proposal_comments')),
    sa.ForeignKeyConstraint(['proposal_id'], ['rule_proposals.id'], name=op.f('fk_proposal_comments_proposal_id_rule_proposals')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proposal_comments'))
    )
    with op.batch_alter_table('proposal_comments', schema=None) as batch_op:
        batch_op.create_index('idx_pcomments_proposal', ['proposal_id', 'created_at'], unique=False)

    op.create_table('proposal_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('ts', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['members.id'], name=op.f('fk_proposal_events_actor_id_members')),
    sa.ForeignKeyConstraint(['proposal_id'], ['rule_proposals.id'], name=op.f('fk_proposal_events_proposal_id_rule_proposals')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proposal_events'))
    )
    with op.batch_alter_table('proposal_events', schema=None) as batch_op:
        batch_op.create_index('idx_pevents_proposal', ['proposal_id', 'ts'], unique=False)

    op.create_table('proposal_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('voter_id', sa.Integer(), nullable=False),
    sa.Column('choice', sa.String(), nullable=False),
    sa.Column('ts', sa.String(), nullable=False),
    sa.CheckConstraint("choice IN ('yes', 'no', 'abstain')", name=op.f('ck_proposal_votes_choice_valid')),
    sa.ForeignKeyConstraint(['proposal_id'], ['rule_proposals.id'], name=op.f('fk_proposal_votes_proposal_id_rule_proposals')),
    sa.ForeignKeyConstraint(['voter_id'], ['members.id'], name=op.f('fk_proposal_votes_voter_id_members')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proposal_votes')),
    sa.UniqueConstraint('proposal_id', 'voter_id', name='one_vote_per_voter')
    )
    with op.batch_alter_table('proposal_votes', schema=None) as batch_op:
        batch_op.create_index('idx_pvotes_proposal', ['proposal_id'], unique=False)

    op.create_table('rule_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('fine_amount', sa.Integer(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('severity_tier', sa.String(), nullable=False),
    sa.Column('auto_confirm', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('proposal_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['members.id'], name=op.f('fk_rule_versions_approved_by_members')),
    sa.ForeignKeyConstraint(['created_by'], ['members.id'], name=op.f('fk_rule_versions_created_by_members')),
    sa.ForeignKeyConstraint(['proposal_id'], ['rule_proposals.id'], name=op.f('fk_rule_versions_proposal_id_rule_proposals')),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], name=op.f('fk_rule_versions_rule_id_rules')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_versions')),
    sa.UniqueConstraint('rule_id', 'version_number', name='one_version_number_per_rule')
    )
    with op.batch_alter_table('rule_versions', schema=None) as batch_op:
        batch_op.create_index('idx_ruleversions_rule', ['rule_id', 'version_number'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proposal_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_notifications_proposal_id_rule_proposals'), 'rule_proposals', ['proposal_id'], ['id'])

    # Add NOT NULL is_active with a server_default so existing rule rows backfill
    # to active(=1); then drop the default to match the model (no server default).
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('1')))
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.alter_column('is_active', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_notifications_proposal_id_rule_proposals'), type_='foreignkey')
        batch_op.drop_column('proposal_id')

    with op.batch_alter_table('rule_versions', schema=None) as batch_op:
        batch_op.drop_index('idx_ruleversions_rule')

    op.drop_table('rule_versions')
    with op.batch_alter_table('proposal_votes', schema=None) as batch_op:
        batch_op.drop_index('idx_pvotes_proposal')

    op.drop_table('proposal_votes')
    with op.batch_alter_table('proposal_events', schema=None) as batch_op:
        batch_op.drop_index('idx_pevents_proposal')

    op.drop_table('proposal_events')
    with op.batch_alter_table('proposal_comments', schema=None) as batch_op:
        batch_op.drop_index('idx_pcomments_proposal')

    op.drop_table('proposal_comments')
    with op.batch_alter_table('rule_proposals', schema=None) as batch_op:
        batch_op.drop_index('idx_proposals_status')
        batch_op.drop_index('idx_proposals_proposer')
        batch_op.drop_index('idx_proposals_closes')

    op.drop_table('rule_proposals')
    # ### end Alembic commands ###
