"""bills declare-confirm lifecycle + bill_events + notifications.bill_id

Revision ID: 7fd6e3f7c889
Revises: c7f3a9e2b1d4
Create Date: 2026-06-27 02:36:24.998614
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7fd6e3f7c889'
down_revision: Union[str, None] = 'c7f3a9e2b1d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('ts', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['members.id'], name=op.f('fk_bill_events_actor_id_members')),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], name=op.f('fk_bill_events_bill_id_bills')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bill_events'))
    )
    with op.batch_alter_table('bill_events', schema=None) as batch_op:
        batch_op.create_index('idx_bill_events_bill', ['bill_id', 'ts'], unique=False)

    with op.batch_alter_table('bills', schema=None) as batch_op:
        # Existing bills are historical/settled -> backfill to 'confirmed' via a temporary
        # server_default (NOT NULL can't be added bare to a populated table).
        batch_op.add_column(sa.Column('status', sa.String(), nullable=False, server_default='confirmed'))
        batch_op.add_column(sa.Column('confirm_deadline', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('disputed_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dispute_reason', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('resolved_at', sa.String(), nullable=True))
        batch_op.create_index('idx_bills_status', ['status'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_bills_disputed_by_members'), 'members', ['disputed_by'], ['id'])

    # Drop the server_default so NEW bills use the app default ('pending').
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.alter_column('status', server_default=None)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bill_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_notifications_bill_id_bills'), 'bills', ['bill_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_notifications_bill_id_bills'), type_='foreignkey')
        batch_op.drop_column('bill_id')

    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_bills_disputed_by_members'), type_='foreignkey')
        batch_op.drop_index('idx_bills_status')
        batch_op.drop_column('resolved_at')
        batch_op.drop_column('dispute_reason')
        batch_op.drop_column('disputed_by')
        batch_op.drop_column('confirm_deadline')
        batch_op.drop_column('status')

    with op.batch_alter_table('bill_events', schema=None) as batch_op:
        batch_op.drop_index('idx_bill_events_bill')

    op.drop_table('bill_events')
    # ### end Alembic commands ###
