"""money ledger: rent shares + ledger_entries + settlements

Revision ID: 897fcadf1707
Revises: 5412e3af0c9d
Create Date: 2026-06-27 10:50:42.401200
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '897fcadf1707'
down_revision: Union[str, None] = '5412e3af0c9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_from', sa.String(), nullable=False),
    sa.Column('period_to', sa.String(), nullable=False),
    sa.Column('monthly_rent', sa.Integer(), nullable=False),
    sa.Column('pot_collected', sa.Integer(), nullable=False),
    sa.Column('applied_to_rent', sa.Integer(), nullable=False),
    sa.Column('leftover', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.CheckConstraint('pot_collected >= 0', name=op.f('ck_settlements_pot_non_negative')),
    sa.ForeignKeyConstraint(['created_by'], ['members.id'], name=op.f('fk_settlements_created_by_members')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settlements'))
    )
    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.create_index('idx_settlements_to', ['period_to'], unique=False)

    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('settlement_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.CheckConstraint("type IN ('advance', 'deposit', 'broker', 'penalty', 'payout', 'adjustment')", name=op.f('ck_ledger_entries_ledger_type_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['members.id'], name=op.f('fk_ledger_entries_created_by_members')),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_ledger_entries_member_id_members')),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlements.id'], name=op.f('fk_ledger_entries_settlement_id_settlements')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_entries'))
    )
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.create_index('idx_ledger_member', ['member_id'], unique=False)

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rent_share_pct', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('rent_share_pct')

    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_index('idx_ledger_member')

    op.drop_table('ledger_entries')
    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.drop_index('idx_settlements_to')

    op.drop_table('settlements')
    # ### end Alembic commands ###
