"""baseline schema

Revision ID: 9a327c01c739
Revises: 
Create Date: 2026-06-26 13:40:39.044594
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9a327c01c739'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('whatsapp', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('joined_on', sa.String(), nullable=False),
    sa.Column('left_on', sa.String(), nullable=True),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("role = 'guest' OR host_id IS NULL", name=op.f('ck_members_host_only_for_guest')),
    sa.CheckConstraint("role IN ('tenant', 'guest')", name=op.f('ck_members_role_valid')),
    sa.ForeignKeyConstraint(['host_id'], ['members.id'], name=op.f('fk_members_host_id_members')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_members')),
    sa.UniqueConstraint('telegram_id', name=op.f('uq_members_telegram_id'))
    )
    # Functional unique index (case-insensitive username) — added by hand because
    # SQLite can't reflect expression indexes, so autogenerate skips it.
    op.create_index('idx_members_username', 'members', [sa.text('lower(username)')], unique=True)
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('fine_amount', sa.Integer(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('severity_tier', sa.String(), nullable=False),
    sa.Column('auto_confirm', sa.Boolean(), nullable=False),
    sa.CheckConstraint("severity_tier IN ('low', 'high')", name=op.f('ck_rules_severity_valid')),
    sa.CheckConstraint('fine_amount >= 0', name=op.f('ck_rules_fine_amount_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rules'))
    )
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.create_index('idx_rules_category', ['category'], unique=False)

    op.create_table('bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('paid_by', sa.Integer(), nullable=True),
    sa.Column('ts', sa.String(), nullable=False),
    sa.CheckConstraint("type IN ('rent', 'house_help', 'electricity', 'water')", name=op.f('ck_bills_type_valid')),
    sa.CheckConstraint('total >= 0', name=op.f('ck_bills_total_non_negative')),
    sa.ForeignKeyConstraint(['paid_by'], ['members.id'], name=op.f('fk_bills_paid_by_members')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bills'))
    )
    op.create_table('fines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('ts', sa.String(), nullable=False),
    sa.Column('added_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('confirm_deadline', sa.String(), nullable=True),
    sa.Column('dispute_reason', sa.String(), nullable=True),
    sa.Column('vote_deadline', sa.String(), nullable=True),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.Column('resolved_at', sa.String(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'confirmed', 'disputed', 'void', 'upheld')", name=op.f('ck_fines_status_valid')),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_fines_amount_non_negative')),
    sa.ForeignKeyConstraint(['added_by'], ['members.id'], name=op.f('fk_fines_added_by_members')),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_fines_member_id_members')),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], name=op.f('fk_fines_rule_id_rules')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fines'))
    )
    with op.batch_alter_table('fines', schema=None) as batch_op:
        batch_op.create_index('idx_fines_addedby', ['added_by'], unique=False)
        batch_op.create_index('idx_fines_member', ['member_id'], unique=False)
        batch_op.create_index('idx_fines_status', ['status'], unique=False)

    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('p256dh', sa.String(), nullable=False),
    sa.Column('auth', sa.String(), nullable=False),
    sa.Column('ts', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_push_subscriptions_member_id_members')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_push_subscriptions')),
    sa.UniqueConstraint('endpoint', name=op.f('uq_push_subscriptions_endpoint'))
    )
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.create_index('idx_push_member', ['member_id'], unique=False)

    op.create_table('bill_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('share_amount', sa.Integer(), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.CheckConstraint('share_amount >= 0', name=op.f('ck_bill_shares_share_non_negative')),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], name=op.f('fk_bill_shares_bill_id_bills')),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_bill_shares_member_id_members')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bill_shares')),
    sa.UniqueConstraint('bill_id', 'member_id', name='one_share_per_member')
    )
    with op.batch_alter_table('bill_shares', schema=None) as batch_op:
        batch_op.create_index('idx_shares_bill', ['bill_id'], unique=False)
        batch_op.create_index('idx_shares_member', ['member_id'], unique=False)

    op.create_table('fine_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fine_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('ts', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['members.id'], name=op.f('fk_fine_events_actor_id_members')),
    sa.ForeignKeyConstraint(['fine_id'], ['fines.id'], name=op.f('fk_fine_events_fine_id_fines')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fine_events'))
    )
    with op.batch_alter_table('fine_events', schema=None) as batch_op:
        batch_op.create_index('idx_events_fine', ['fine_id', 'ts'], unique=False)

    op.create_table('fine_proofs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fine_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('ref', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('ts', sa.String(), nullable=False),
    sa.CheckConstraint("source IN ('upload', 'telegram')", name=op.f('ck_fine_proofs_source_valid')),
    sa.ForeignKeyConstraint(['fine_id'], ['fines.id'], name=op.f('fk_fine_proofs_fine_id_fines')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['members.id'], name=op.f('fk_fine_proofs_uploaded_by_members')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fine_proofs'))
    )
    with op.batch_alter_table('fine_proofs', schema=None) as batch_op:
        batch_op.create_index('idx_proofs_fine', ['fine_id'], unique=False)

    op.create_table('fine_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fine_id', sa.Integer(), nullable=False),
    sa.Column('voter_id', sa.Integer(), nullable=False),
    sa.Column('vote', sa.String(), nullable=False),
    sa.Column('ts', sa.String(), nullable=True),
    sa.CheckConstraint("vote IN ('uphold', 'void')", name=op.f('ck_fine_votes_vote_valid')),
    sa.ForeignKeyConstraint(['fine_id'], ['fines.id'], name=op.f('fk_fine_votes_fine_id_fines')),
    sa.ForeignKeyConstraint(['voter_id'], ['members.id'], name=op.f('fk_fine_votes_voter_id_members')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fine_votes')),
    sa.UniqueConstraint('fine_id', 'voter_id', name='one_vote_per_voter')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('fine_id', sa.Integer(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('ts', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['fine_id'], ['fines.id'], name=op.f('fk_notifications_fine_id_fines')),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_notifications_member_id_members')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('idx_notif_member', ['member_id', 'read', 'ts'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('idx_notif_member')

    op.drop_table('notifications')
    op.drop_table('fine_votes')
    with op.batch_alter_table('fine_proofs', schema=None) as batch_op:
        batch_op.drop_index('idx_proofs_fine')

    op.drop_table('fine_proofs')
    with op.batch_alter_table('fine_events', schema=None) as batch_op:
        batch_op.drop_index('idx_events_fine')

    op.drop_table('fine_events')
    with op.batch_alter_table('bill_shares', schema=None) as batch_op:
        batch_op.drop_index('idx_shares_member')
        batch_op.drop_index('idx_shares_bill')

    op.drop_table('bill_shares')
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.drop_index('idx_push_member')

    op.drop_table('push_subscriptions')
    with op.batch_alter_table('fines', schema=None) as batch_op:
        batch_op.drop_index('idx_fines_status')
        batch_op.drop_index('idx_fines_member')
        batch_op.drop_index('idx_fines_addedby')

    op.drop_table('fines')
    op.drop_table('bills')
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.drop_index('idx_rules_category')

    op.drop_table('rules')
    op.drop_index('idx_members_username', table_name='members')
    op.drop_table('members')
    # ### end Alembic commands ###
